/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.38
 * Generated at: 2016-11-17 03:54:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class request_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("utf-8"); 
      out.write('\r');
      out.write('\n');

	Connection conn = null;
	PreparedStatement pstmt = null;

	String jdbc_driver = "com.mysql.jdbc.Driver";
	String jdbc_url = "jdbc:mysql://localhost/jspdb";
	String id=request.getParameter("id");
	String password;

	try{
	Class.forName(jdbc_driver);

	conn = DriverManager.getConnection(jdbc_url,"dmdoa12","gmltjd12");
	String sql = "select passwd from user where id = ?";
	pstmt = conn.prepareStatement(sql);
	pstmt.setString(1, id);

	ResultSet rs = pstmt.executeQuery();
	
		if(rs.getString("passwd")==null){
			session.setAttribute("check", "fail");
		}
		else{
		rs.next();
		password = rs.getString("passwd");
		rs.close();
			
			if (request.getParameter("pw").equals(password)) {
			session.setAttribute("check", "sucess");
			session.setAttribute("userid",id);
			}
		}	
	}
	catch(Exception e){
		System.out.println(e);
	}

conn.close();


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>수강신청</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t");

		if (session.getAttribute("check").equals("sucess")) {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.print(session.getAttribute("userid"));
      out.write("님 로그인 하셨습니다.<a href=\"MidTerm_logout.jsp\">로그아웃</a>\r\n");
      out.write("\r\n");
      out.write("\t");

		} else {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t로그인을 하지 않으셨습니다.<a href=\"MidTerm_login.jsp\">로그인</a>\r\n");
      out.write("\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("<h2>2017년 1학기 수강신청</h2>\r\n");
      out.write("<form name=\"dataInput\" method=\"post\"\r\n");
      out.write("action=\"MidTerm_sugang_result.jsp\">\r\n");
      out.write("<table border=\"1\" align=\"center\">\r\n");
      out.write("\t<!-- 이름 -->\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"100\">이름</td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"name\" size=\"50\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<!-- 학번 -->\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"100\">학번</td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"student_num\" size=\"50\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<!-- 과목 -->\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"100\">과목</td>\r\n");
      out.write("\t\t<td><input type=\"checkbox\" name=\"subject\" value=\"Java\" />Java\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"subject\" value=\"Database\" />Database\r\n");
      out.write("\t\t\t<input type=\"checkbox\" name=\"subject\" value=\"Jsp\" />Jsp <input\r\n");
      out.write("\t\t\ttype=\"checkbox\" name=\"subject\" value=\"Iot\" />Iot <input\r\n");
      out.write("\t\t\ttype=\"checkbox\" name=\"subject\" value=\"Android\" />Android</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<!-- 버튼 -->\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" align=\"center\"><input type=\"submit\"\r\n");
      out.write("\t\t\t\tvalue=\"수강신청\"> <input type=\"reset\" value=\"수강취소\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br> <a href=\"MidTerm_sugang_total.jsp\">현재 과목 수강 신청 현황</a>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
